# Generated by Django 5.0.2 on 2024-04-19 21:31

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Duenos',
            fields=[
                ('codigo_dueno', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('telefono', models.CharField(max_length=10, validators=[django.core.validators.RegexValidator('^\\d{1,10}$')])),
                ('direccion', models.CharField(max_length=255)),
                ('correo_electronico', models.EmailField(max_length=254)),
                ('estado', models.CharField(choices=[('active', 'ACTIVE'), ('inactive', 'INACTIVE')], default='active', max_length=10)),
            ],
            options={
                'verbose_name_plural': 'Duenos',
            },
        ),
        migrations.CreateModel(
            name='Mascotas',
            fields=[
                ('codigo_mascota', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('fecha_nacimiento', models.DateField()),
                ('sexo', models.CharField(max_length=1)),
                ('especie', models.CharField(max_length=50)),
                ('raza', models.CharField(max_length=50)),
                ('estado', models.CharField(choices=[('active', 'ACTIVE'), ('inactive', 'INACTIVE')], default='active', max_length=10)),
                ('codigo_dueno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Veterinaria.duenos')),
            ],
            options={
                'verbose_name_plural': 'Mascotas',
            },
        ),
        migrations.CreateModel(
            name='Desparasitaciones',
            fields=[
                ('codigo_desparacitacion', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField()),
                ('tipo', models.CharField(max_length=50)),
                ('nombre', models.CharField(max_length=50)),
                ('via_administracion', models.CharField(max_length=50)),
                ('estado', models.CharField(choices=[('completed', 'COMPLETED'), ('incompleted', 'INCOMPLETED'), ('pending', 'PENDING')], default='pending', max_length=11)),
                ('codigo_mascota', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Veterinaria.mascotas')),
            ],
            options={
                'verbose_name_plural': 'Fichas de Desparacitacion',
            },
        ),
        migrations.CreateModel(
            name='Citas',
            fields=[
                ('codigo_cita', models.AutoField(primary_key=True, serialize=False)),
                ('fechaHora', models.DateTimeField()),
                ('razon_cita', models.CharField(max_length=255)),
                ('estado', models.CharField(choices=[('done', 'DONE'), ('canceled', 'CANCELED'), ('pending', 'PENDING')], default='pending', max_length=10)),
                ('codigo_mascota', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Veterinaria.mascotas')),
            ],
            options={
                'verbose_name_plural': 'Citas',
            },
        ),
    ]
